[versions]
kotlin = "2.1.20"
paper = "2.0.0-beta.18"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paper = { id = "io.papermc.paperweight.userdev", version.ref = "paper" }
